### ISSUE TITLE
Write out optimized bdf files including loads

### ISSUE THREAD

**Issue by timryanb** [smdogroup/tacs#172]
Right now we don't provide users any methods for exporting their optimized models/loads back out in a BDF file format. In theory, this shouldn't be to difficult if we take advantage of pynastran's BDF class, which gets created in the pymeshloader. We'll have to figure out a way to propagate current dv information as well as problem loads back to the BDF class in order to update them in the BDF file before it is exported

**Comment by jaredmagnusson** [comment]
Does this enhancement allow outputs of displacement variables such as u,v,w, and v3? I'm investigating writing to BDF rather than f5 but I don't see these variables (or I just don't know how to access them yet) in the output bdf.

**Comment by jaredmagnusson** [comment]
Good to know, thank you!
