### ISSUE TITLE
Windows install instructions

### ISSUE THREAD

**Issue by andrewellis55** [smdogroup/tacs#178]
Are there any Windows install instructions for TACs? I didn't explicitly see it stated that it's linux/OSX only, however I did see that there are only conda builds for those two so I wasn't sure

**Comment by timryanb** [comment]
Unfortunately, at this point, TACS has no direct support for windows systems, only Linux/OSX.

If you want to be able to run TACS on a Windows system your best bet is probably going to be:

1. Install a Linux-based Virtual Machine (VM) and install and access TACS through there
2. Install [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install) and install and access TACS through there

For either 1 or 2 any of the installation methods described in the docs should get you setup with TACS

**Comment by A-CGray** [comment]
Another option would be to install docker and then use one of the [MDO Lab's public docker images](https://github.com/mdolab/docker), which include TACS.

**Comment by andrewellis55** [comment]
Ok thank you both!

**Comment by hntter** [comment]
> Another option would be to install docker and then use one of the [MDO Lab's public docker images](https://hub.docker.com/r/mdolab/public), which include TACS.

Hello, 

May I ask how to convert results file *.f5 get from TACS to *.plt in MDO docker images? I typed the command $ f5totec but it showed "bash: f5totec: command not found".  How can I fix this?

best wishes

**Comment by A-CGray** [comment]
You will need to compile f5totec yourself, instructions are [here](https://smdogroup.github.io/tacs/install.html#install-postprocessing-tools)
