### ISSUE TITLE
Segmentation fault with f5totec/f5tovtk

### ISSUE THREAD

**Issue by Gil231b** [smdogroup/tacs#181]
Hello, 

I followed the instructions in the documentation to install `tacs` in with conda in a linux machine. Everything seems to be installed properly, but when I try to convert my `f5` file using either `fttotec` or `f5tovtk` I get an exception:
```bash
(TACS) -bash-4.4$ f5tovtk solution.f5
Trying to convert FH5 file solution.f5 to vtk file solution.vtk
Segmentation fault (core dumped)
```
```bash
(TACS) -bash-4.4$ f5totec solution.f5
Trying to convert FH5 file solution.f5 to tecplot file solution.plt
Segmentation fault (core dumped)
```
I am using version tacs v. `3.2.0` 

In the case of `f5tovtk` I see that an empty file is created with the name `solution.vtk`, `f5totec` does not even create an output file.

Do you have any suggestions on how to solve this? I looked for tests on the source code but I could not find any.

Thanks in advance.

**Comment by timryanb** [comment]
How was the `f5` file you're converting generated? Is this an `f5` file generated from one of the examples or a new analysis you've created?

**Comment by Gil231b** [comment]
It's a new analysis, it was generated using [pytacs](https://github.com/mdolab/pytacs).

**Comment by timryanb** [comment]
It looks like you're pointing to the pyTACS wrapper for TACS 1. f5 files generated by TACS 1 are not backwards-compatible with TACS 3. You'll have to use the `f5totec` that was compiled against the TACS 1 source code.

**Comment by Gil231b** [comment]
I see, thank you for your help. I think we can close this issue now.
