### ISSUE TITLE
Building f5totec cannot link against libtacs

### ISSUE THREAD

**Issue by nwukie** [smdogroup/tacs#214]
Attempting to build f5totec (e.g. cd extern/f5totec; make), the build seems to not be set up correctly to link the tacs library as shown by the following link error:

```
mpicxx f5totec.o /home/minion/local/tecio/install/libtecio*.a  -L/lib/ -Wl,-rpath,/lib -ltacs  /home/minion/local/metis/lib/libmetis.a -L/opt/intel/oneapi/mkl/2023.0.0/lib/intel64 -L/opt/intel/oneapi/mkl/2023.0.0/../../compiler/latest/linux/compiler/lib/intel64_lin -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -o f5totec
/usr/bin/ld: cannot find -ltacs
collect2: error: ld returned 1 exit status
make: *** [Makefile:9: f5totec] Error 1
```

I was able to fix by amending extern/f5totec/Makefile to include -L../../lib so that the linker would have visibility to the tacs library. I don't know if that is the preferred approach or if one should be building it differently.

**Comment by timryanb** [comment]
This linking should be handled automatically (see [here](https://github.com/smdogroup/tacs/actions/runs/5028596707/jobs/9019463326#step:6:63) and [here](https://github.com/smdogroup/tacs/blob/master/Makefile.in.info#L29)). Did you properly set the [`TACS_DIR`](https://github.com/smdogroup/tacs/blob/master/Makefile.in.info#L8) variable in your Makefile.in?

**Comment by nwukie** [comment]
Yes, I was creating Makefile.in programmatically and TACS_DIR was errantly getting evaluated to an empty string. Fixed the process and all is well. Thanks for the recommendation.
