### ISSUE TITLE
Conda installation not up to date

### ISSUE THREAD

**Issue by peter-greaves** [smdogroup/tacs#237]
I've noticed that the Anaconda install isn't current to the source code - when I tried to run buckling examples I found that the Buckling class can't be imported on my conda install (and isn't in the site-packages/tacs folder) but if I download the source then it is there.

**Comment by timryanb** [comment]
What version are you using? The anaconda package (3.3.
1) was just deployed last week,  so it's pretty current and should have the buckling class available

**Comment by peter-greaves** [comment]
Not sure what was going on there, I only followed the install instructions this week and I ended up getting 3.3.0 installed, and it reinstalled the same version when I installed it. When I ran it just now after doing  conda update -c conda-forge -c smdogroup tacs I have 3.3.1.
