### ISSUE TITLE
Initialize/Update pyTACS FEAAssembler from BDF object?

### ISSUE THREAD

**Issue by jaredmagnusson** [smdogroup/tacs#243]
Is there a way to initialize or update a pyTACS object from a pyNastran BDF instance, rather than a BDF file? 

I'm looking to run a large number of thermal deformation cases for various trade studies, and the runs only differ in initial temperature constraints. 

Right now, for each run we are saving a separate BDF file with different SPC temperature cards assigned to it before running TACS. This is getting inefficient as our number of cases grows the file I/O becomes a large fraction of the runtime.

**Comment by jaredmagnusson** [comment]
That would be excellent yes, re-initializing should be fine.

**Comment by timryanb** [comment]
The feature should be added once PR #245 is merged in

**Comment by jaredmagnusson** [comment]
Thank you so much

**Comment by timryanb** [comment]
Closing due to PR #245 being merged
