### ISSUE TITLE
Orthotropic heat conduction in shell elements

### ISSUE THREAD

**Issue by Pranav4495** [smdogroup/tacs#249]
Hi,

I believe the current version can handle heat conduction problems with isotropic thermal conductivities (kappa). Specifying kappa1 and kappa2 instead of kappa will resort to the predefined value of kappa in the code. Is there a way to use kappa1 and kappa2 in 2D and kappa1, kappa2 and kappa3 in 3D conduction problems?

Thanks,
Pranav

**Comment by timryanb** [comment]
It looks like there was an oversight in how orthotropic properties are handled in the `MaterialProperties` class (see [here](https://github.com/smdogroup/tacs/blob/master/tacs/constitutive.pyx#L316-L324)). It looks like the code uses decides whether or not the provided properties are orthotropic or not based on if the 1-1 Young's modulus "E1" is included in kwargs. 
Obviously, you shouldn't need to provide this parameter for a purely thermal analysis, so in the future we can fix this to make it more general. 

 In the meantime, if you add E1 to your kwargs when instantiating your `MaterialProperties` (even if you don't need it), you should get the orthotropic properties you're expecting.

```
prop = MaterialProperties(E1=1.0, kappa1=1e-6, kappa2=2e-6, ....)
```

**Comment by Pranav4495** [comment]
That clarifies it. Thanks for the quick response. I will try and let you know how it goes.

**Comment by Pranav4495** [comment]
I tried the 'thermal_plate' example by specifying E1 and using kappa1=kappa2=kappa. Ideally, it should yield the same results as specifying kappa=kappa, but it seems there are convergence issues with the solver, probably due to ill-conditioning. Please see the attached image. I have tried a different analysis, giving similar issues.

Additionally, I have a few questions/comments on the problem setup.

1. Is there a way to define lamina ply angles and material properties as design variables? If so, will the sensitivities w.r.t these variables be calculated internally?
2. I am trying to use the buckling solver with sigma=0 (shift-invert mode), giving all zero eigenvalues for the first 10 modes, whereas specifying a non-zero small positive sigma yields eigenvalues that are very different from what I get using Nastran. The static analysis part of the same problem works fine, so I am wondering if there is anything I am missing in the problem buckling problem definition. 

<img width="648" alt="ht_ortho_illcondition" src="https://github.com/smdogroup/tacs/assets/70219987/88354b2b-6402-4466-9ff5-910259086314">

**Comment by timryanb** [comment]
Could you attach your code and bdf model for reference. As of right now, I don't believe thermal elements are supported in the buckling eigenvalue solver. @gjkennedy can fact check me on this. If thermal buckling would be a desired feature, can you create a new issue for that specific topic? It'll make it easier for us to bookkeep that way

**Comment by Pranav4495** [comment]
> Could you attach your code and bdf model for reference. As of right now, I don't believe thermal elements are supported in the buckling eigenvalue solver. @gjkennedy can fact check me on this. If thermal buckling would be a desired feature, can you create a new issue for that specific topic? It'll make it easier for us to bookkeep that way

The thermal analysis and buckling analysis comments are for different problems (Sorry for not creating a separate issue for buckling). The buckling analysis is done under mechanical loads as of now, for which I managed to fix the issue with my code.

For thermal analysis, I have used the [thermal plate](https://github.com/smdogroup/tacs/tree/master/examples/thermal_plate) example and defined E1=1 and kappa1=kappa2=kappa in the code.

**Comment by timryanb** [comment]
Thanks, for pointing this out. This was definitely a bug where kappa was never actually being saved in the MaterialProperties class. PR #252 should fix this issue

**Comment by Pranav4495** [comment]
That sounds great! Thanks for your effort in looking into this.
